mod rclone;
pub(crate) use rclone::RcloneTransferStats;
pub(crate) mod artifacts;
mod cloud_api;
pub(crate) mod config;
mod http_cache;
pub(crate) mod metadata;
mod repo;
mod service;
pub(crate) use service::Downloader;
pub(crate) mod downloads_catalog;
pub(crate) mod manager;
