mod rclone;
pub(crate) use rclone::RcloneTransferStats;
mod cloud_api;
pub(crate) mod config;
pub(crate) mod download_metadata;
mod http_cache;
mod repo;
mod service;
pub(crate) use service::Downloader;
pub(crate) mod downloads_catalog;
pub(crate) mod service_manager;
